### ISSUE TITLE
Control Laws

### ISSUE THREAD

**Issue by FranciiscoSilva** [sotpapathe/UAV-Coverage#1]
Hi, sorry to reach you through here. I have a question, where did u pulled out the control laws, you created your own, you got it from anywhere ?

Cumps 
p.s.-  btw on the readme.m u have twice the function "UAV_coverage_uniform_quality" while one of them should be ""UAV_coverage_uniform_quality_phi"

**Comment by sotpapathe** [comment]
The control laws were derived specifically for this case. They are explained in detail in the articles in the References section of the REAME
